name: Deploy

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install dependencies
        run: yarn install
      # - name: Run Lint
      #   run: yarn run lint
      - name: Build
        run: |
          yarn run generate
          ls /home/runner/work/coyo/coyo
      - name: Deploy to S3
        uses: docker://amazon/aws-cli:2.0.7
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          args: s3 sync /github/workspace/dist s3://coyo.dev --delete --endpoint-url https://s3.fr-par.scw.cloud
